name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main # Or the branch you want to deploy from

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20 # Or your required version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm i

      - name: Build Next.js ${{ secrets.PROJECT_NAME }}
        run: npm run cfbuild

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Workers
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy
